import type { Metadata } from 'next';
import { NotosansFont } from '@/common/font';
import '@/styles/globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={NotosansFont.className}>{children}</body>
    </html>
  );
}
